Asp.net-recepy-blog/Pages/About.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Asp.net_recepy_blog.Pages
{
    public class AboutModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Asp.net-recepy-blog/Pages/Account.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Asp.net_recepy_blog.Pages.Services;
using Asp.net_recepy_blog.Pages.Dbcontrol;
using Microsoft.Extensions.Hosting;

namespace Asp.net_recepy_blog.Pages
{
    public class AccountModel : PageModel
    {
        private readonly IUserServices _userService;
        private readonly MyDbContext _dbContext;
        private readonly EmailServices _emailService;
        private readonly PostsServices _postsService;
        public AccountModel(IUserServices userService, MyDbContext dbContext, EmailServices emailService, PostsServices postsService)
        {
            _userService = userService;
            _dbContext = dbContext;
            _emailService = emailService;
            _postsService = postsService;
        }
        public async Task<IActionResult> OnGetAsync()
        {
            if (HttpContext.Session.GetString("UserId") != null)
            {
                int userId = int.Parse(HttpContext.Session.GetString("UserId"));
                var user = await _userService.GetUserByIdAsync(userId);
                ViewData["User"] = user;
            }
            else
            {
                ViewData["User"] = null;
            }

            return Page();
        }

        [BindProperty]
        public User UserC { get; set; }
        public async Task<IActionResult> OnPostUpdatePasswordAsync(int userId)
        {
            var user = await _userService.GetUserByIdAsync(userId);
            if (UserC.Name != null)
            {
                user.Name = UserC.Name;
            }
            if (UserC.Password != null)
            {
                user.Password = UserC.Password;
            }
            if (UserC.Email != null)
            {
                await _emailService.SendEmailAsync(user.Email, "Данные аккаунта изменились!", "Вы сменили свою электронную почту, теперь уведомления не будут приходить на эту почту.");
                user.Email = UserC.Email;
                await _emailService.SendEmailAsync(user.Email, "Данные аккаунта изменились!", "Это ваша новая электронная почта привязанная сайту по обмену рецептами.");
            }
            await _dbContext.SaveChangesAsync();

            return RedirectToPage("/Account");
        }

        public async Task<IActionResult> OnPostDeleteAccountAsync(int userId)
        {
            var user = await _userService.GetUserByIdAsync(userId);
            if (user == null)
            {
                return NotFound();
            }

            var posts = await _postsService.GetPostByUserIdAsync(userId);
            foreach(var post in posts)
            {
                _dbContext.Posts.Remove(post);
            }
            await _dbContext.SaveChangesAsync();

            await _userService.DeleteUserAsync(userId);
            HttpContext.Session.Clear();
            return RedirectToPage("/Account");
        }

        public async Task<IActionResult> OnPostLogoutAsync()
        {
            HttpContext.Session.Clear();
            return RedirectToPage("/Account");
        }

        //изменение запсей

        [BindProperty]
        public string PostName { get; set; }

        [BindProperty]
        public string Ingredients { get; set; }

        [BindProperty]
        public string Cookingmethod { get; set; }

        public async Task<IActionResult> OnPostUpdatePostAsync(int postId)
        {
            if (HttpContext.Session.GetString("UserId") != null)
            {
                int userId = int.Parse(HttpContext.Session.GetString("UserId"));
                var user = await _userService.GetUserByIdAsync(userId);

                var post = await _dbContext.Posts.FindAsync(postId);
                if (post != null)
                {
                    post.Name = PostName;
                    post.Ingredients = Ingredients;
                    post.CookingMethod = Cookingmethod;
                    _dbContext.Posts.Update(post);
                }
            }

            await _dbContext.SaveChangesAsync();

            return RedirectToPage("/Account");
        }

        public async Task<IActionResult> OnPostDeletePostAsync(int postId)
        {
            var post = await _dbContext.Posts.FindAsync(postId);
            if (post == null)
            {
                return NotFound();
            }

            _dbContext.Posts.Remove(post);
            await _dbContext.SaveChangesAsync();

            return RedirectToPage("/Account");
        }


    }
}

Asp.net-recepy-blog/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace Asp.net_recepy_blog.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }

}

Asp.net-recepy-blog/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;
using Asp.net_recepy_blog.Pages.Services;
using Asp.net_recepy_blog.Pages.Dbcontrol;
using Microsoft.Extensions.Hosting.Internal;

namespace Asp.net_recepy_blog.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        private readonly IUserServices _userService;
        private readonly MyDbContext _context;
        private readonly EmailServices _emailService;
        private IWebHostEnvironment _hostingEnvironment;

        public IndexModel(ILogger<IndexModel> logger, MyDbContext context, EmailServices emailService, UserServices userService, IWebHostEnvironment hostingEnvironment)
        {
            _hostingEnvironment = hostingEnvironment;
            _context = context;
            _emailService = emailService;
            _userService = userService;
            _logger = logger;
            newPost = new Posts();
        }

        [BindProperty]
        public Posts newPost { get; set; }

        [BindProperty]
        public IFormFile photo { get; set; }

        public void OnGet()
        {

        }

        [HttpPost]
        public async Task<IActionResult> OnPostAsync()
        {
            Console.WriteLine("Toggeled AddPost");
            Console.WriteLine($"Post: {newPost.Name}, {newPost.PostId}");
            if (photo != null && photo.Length > 0)
            {
                var fileName = Path.GetFileName(photo.FileName);
                string directoryPath = Path.Combine(_hostingEnvironment.WebRootPath, "imgs");

                var filePath = Path.Combine(directoryPath, fileName);
                try
                {
                    using (var fileStream = new FileStream(filePath, FileMode.Create))
                    {
                        await photo.CopyToAsync(fileStream);
                    }
                    newPost.PhotoPath = Path.GetFileName(filePath);
                }
                catch (Exception ex)
                {
                    Console.WriteLine($"Ошибка сохранения картинки: {ex.Message}");
                    // Обработка исключения, например, можно установить путь к запасной картинке
                    newPost.PhotoPath = "default.png";
                }
            }
            else
            {
                newPost.PhotoPath = "default.png";
            }
            _context.Posts.Add(newPost);
            await _context.SaveChangesAsync();
            return RedirectToPage("Index");
        }


    }
}

Asp.net-recepy-blog/Pages/Login.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Asp.net_recepy_blog.Pages.Services;
using Asp.net_recepy_blog.Pages.Dbcontrol;
using System.Text.RegularExpressions;

namespace Asp.net_recepy_blog.Pages
{
    public class LoginModel : PageModel
    {
        public void OnGet()
        {
        }
        private readonly IUserServices _userService;
        private readonly MyDbContext _context;
        private readonly EmailServices _emailService;

        [BindProperty]
        public string Action { get; set; }

        //Регистрация

        [BindProperty]
        public User User { get; set; }

        //Вход
        [BindProperty]
        public string Email { get; set; }

        [BindProperty]
        public string Password { get; set; }

        public LoginModel(MyDbContext context, EmailServices emailService, UserServices userService)
        {
            _context = context;
            _emailService = emailService;
            _userService = userService;
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (Action == "register")
            {
                var existingUser = await _userService.GetUsersByEmailAsync(User.Email);
                if (existingUser.Any())
                {
                    ModelState.AddModelError("User.Email", "Пользователь с такой почтой уже существует.");
                    return Page();
                }

                if (!Regex.IsMatch(User.Password, @"^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[\W_]).*$"))
                {
                    ModelState.AddModelError("User.Password", "Пароль должен содержать заглавные и строчные буквы, цифры и специальные символы");
                    return Page();
                }

                await _userService.AddUserAsync(User);
                await _emailService.SendEmailAsync(User.Email, "Поздравляем!", $"Теперь вы загегистрированный в нашей соицальной сети и сможете делится своими или читать чужие рецепты вкуснейшей еды!");
                return RedirectToPage("/Account");
            }
            else
            {
                var users = await _userService.GetUsersByEmailAsync(Email);
                if (users.Count > 0)
                {
                    var user = users.First();
                    if (user.Password == Password)
                    {
                        HttpContext.Session.SetString("UserId", user.UserId.ToString());
                        return RedirectToPage("/Account");
                    }
                    else
                    {
                        ModelState.AddModelError("Password", "Не корректный пароль.");
                        return Page();
                    }
                }
                else
                {
                    ModelState.AddModelError("Email", "Пользователь не найден.");
                    return Page();
                }
            }
        }
    }
}

Asp.net-recepy-blog/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Asp.net_recepy_blog.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }

}

Asp.net-recepy-blog/Pages/About.cshtml
@page
@model Asp.net_recepy_blog.Pages.AboutModel
@{
    ViewData["Title"] = "О нас";
}
<div class="m-4">

    <div class="row pt-4 pb-4">
        <div class="col">
            <img src="/imgs/about-img.jpg" class="border-end border-3" />
        </div>
        <div class="col d-flex flex-md-column justify-content-center">
            <h1 class="mt-4 mb-4">О нас</h1>
            <p class="mt-3 mb-3">Добро пожаловать на нашу страничку, любители и новички обмена рецептами!</p>
            <p class="text-justify">
                Мы с гордостью можем сказать, что на нашем сайте находится лучшая в мире
                коллекция рецептов! Каждый рецепт, находящийся на сайте, обязательно будет
                потрясающий!
                Не верьте нам на слово! Посетите нас в Yelp, Facebook, Twitter и где угодно!
                Опубликовано в журнале Cooking Light (журнал Time — награда Cross-
                Cultural Mash-Up, 2013), в нескольких выступлениях в Houston Press,
                в телесериале «Азиатские отбивные» и в множестве других национальных
                изданий и средств массовой информации! Загляните и узнайте, чем в восторге
                все ваши друзья!
            </p>
            <ul class="navbar-nav d-inline-flex flex-row gap-5">
                <li><a href="https://facebook.com"><img src="/imgs/Facebook.svg" alt="Facebook" /></a></li>
                <li><a href="https://x.com/?lang=en"><img src="/imgs/Twitter.svg" alt="X" /></a></li>
                <li><a href="https://www.instagram.com"><img src="/imgs/Instagram.svg" alt="Instagram" /></a></li>
            </ul>
        </div>
    </div>

</div>

Asp.net-recepy-blog/Pages/Account.cshtml
@page
@model Asp.net_recepy_blog.Pages.AccountModel
@inject MyDbContext DbContext
@using Microsoft.EntityFrameworkCore;
@using Microsoft.AspNetCore.Mvc;
@using Microsoft.AspNetCore.Mvc.RazorPages;
@using Asp.net_recepy_blog.Pages.Services;
@using Asp.net_recepy_blog.Pages.Dbcontrol;
@{

    ViewData["Title"] = "Личный кабинет";
    var user = ViewData["User"] as User;

}

<div class="container">
    <div class="m-4">
        @if (HttpContext.Session.GetString("UserId") != null)
        {

            <div class="pt-4 d-flex justify-content-center flex-column align-items-center">
                @foreach (var post in DbContext.Posts.Where(t => t.UserId == int.Parse(HttpContext.Session.GetString("UserId"))))
                {
                    <div class="card my-3 p-3" style="width: 50%;">
                        <h2>@post.Name</h2>
                        <img src="@("/imgs/" + post.PhotoPath)" width="300px" height="300px" />
                        <p>@post.Ingredients</p>
                        <p>@post.CookingMethod</p>
                        <button class="btn btn-outline-info mt-2" onclick="togglePostEditMenu('@post.PostId')">Изменить данные записи</button>
                        <div id="editMenu_@post.PostId" style="display: none;" class="pt-4">
                            <form method="post" asp-page-handler="UpdatePost">
                                <input type="hidden" name="postId" value="@post.PostId" />
                                <div class="form-group">
                                    <label>Название</label>
                                    <input asp-for="PostName" value="@post.Name" class="form-control" />
                                </div>
                                <div class="form-group mt-2">
                                    <label>Ингредиенты</label>
                                    <input asp-for="Ingredients" value="@post.Ingredients" class="form-control" />
                                </div>
                                <div class="form-group mt-2">
                                    <label>Способ приготовления</label>
                                    <input asp-for="Cookingmethod" value="@post.CookingMethod" class="form-control" />
                                </div>
                                <button type="submit" class="btn btn-success mt-2">Сохранить изменения</button>
                            </form>
                            <form method="post" asp-page-handler="DeletePost" class="pt-3">
                                <input type="hidden" name="postId" value="@post.PostId" />
                                <button type="submit" class="btn btn-danger">Удалить запись</button>
                            </form>

                        </div>

                    </div>
                }
            </div>

            <button onclick="toggleSettingsVisibility()" class="btn btn-outline-secondary mt-2 pb-2 mb-3">Настройки пользователя</button>
            <div id="Settings" style="display: none;">
                <form method="post" asp-page-handler="UpdatePassword" class="pt-2 align-content-center d-flex justify-content-center w-100">
                    <div class="w-50 text-start">
                        <input type="hidden" name="userId" value="@HttpContext.Session.GetString("UserId")" />

                        <div class="form-group pb-3 w-100">
                            <label asp-for="UserC.Email">Почта</label>
                            <input asp-for="UserC.Email" class="form-control" />
                            <span asp-validation-for="UserC.Email" class="text-danger"></span>
                        </div>
                        <div class="form-group pb-3 w-100">
                            <label asp-for="UserC.Name">Имя</label>
                            <input asp-for="UserC.Name" class="form-control input-dark" />
                            <span asp-validation-for="UserC.Name" class="text-danger"></span>
                        </div>
                        <div class="form-group pb-3 w-100">
                            <label asp-for="UserC.Password">Пароль</label>
                            <input asp-for="UserC.Password" class="form-control" />
                            <span asp-validation-for="UserC.Password" class="text-danger"></span>
                        </div>
                        <button type="submit" class="btn btn-primary pt-2 mb-4">Сменить данные</button>
                    </div>
                </form>
                <div class="d-flex justify-content-center">
                    <form method="post" asp-page-handler="Logout" class="m-4">
                        <button type="submit" class="btn btn-danger">Выйти</button>
                    </form>
                    <form id="deleteForm" method="post" class="m-4" asp-page-handler="DeleteAccount">
                        <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#deleteModal">Удалить аккаунт</button>
                        <input type="hidden" name="userId" value="@HttpContext.Session.GetString("UserId")" />
                    </form>
                </div>
            </div>

            // modal
            <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog bg-dark">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">Подтверждение</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                            Вы уверенны что хотите удалить аккаунт?
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть</button>
                            <button type="button" class="btn btn-primary" onclick="confirmDelete()">Подтвердить</button>
                        </div>
                    </div>
                </div>
            </div>
        }
        else
        {
            <div class="m-4 d-flex justify-content-center align-items-center mb-0">
                <a class="btn text-body-secondary fs-5 fw-bold" asp-area="" asp-page="/Login">Войдите или зарегистрируйтесь</a>
            </div>
        }
    </div>
</div>

@section Scripts {
    <script>
        function confirmDelete() {
            if (confirm('Вы уверены, что хотите удалить свой аккаунт? Это действие нельзя отменить.')) {
                document.getElementById('deleteForm').submit();
            }
        }

        function toggleSettingsVisibility() {
            var settingsContainer = document.getElementById('Settings');
            if (settingsContainer.style.display === 'none') {
                settingsContainer.style.display = 'block';
            } else {
                settingsContainer.style.display = 'none';
            }
        }

        var myModal = document.getElementById('deleteModal')
        var myInput = document.getElementById('myInput')

        myModal.addEventListener('shown.bs.modal', function () {
            myInput.focus()
        })

        let openRecipes = new Set();

        function togglePostEditMenu(postId) {
            var editMenu = document.getElementById('editMenu_' + postId);
            if (editMenu.style.display === 'none') {
                editMenu.style.display = 'block';
            } else {
                editMenu.style.display = 'none';
            }
        }

        let editMenus = {};

    </script>
}

Asp.net-recepy-blog/Pages/Index.cshtml
@page
@model IndexModel
@inject MyDbContext DbContext
@using Asp.net_recepy_blog.Pages.Services;
@using Asp.net_recepy_blog.Pages.Dbcontrol;
@{
    ViewData["Title"] = "Рецепты";
}
<div class="container">
@*     <form class="d-inline-flex my-2 my-lg-0 w-100" onsubmit="event.stopPropagation(); searchPosts(event);">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-secondary my-2 my-sm-0 m-3" type="submit">Search</button>
    </form> *@
    <div class="pt-4 d-flex justify-content-center">
        @if (HttpContext.Session.GetString("UserId") != null)
        {
            <button onclick="toggleSettingsVisibility()" class="btn btn-outline-secondary mt-2 mb-3">Добавить новый рецепт</button>
            <div id="Addpost" style="display: none !important;" class="addpost p-4 w-25">
                <form method="post" enctype="multipart/form-data">
                    <input type="hidden" asp-for="newPost.UserId" value="@HttpContext.Session.GetString("UserId")" />
                    <div class="form-group pt-3">
                        <label asp-for="newPost.Name">Название</label>
                        <input asp-for="newPost.Name" class="form-control w-100" />
                    </div>
                    <div class="form-group pt-3 pb-3">
                        <label asp-for="photo">Фото</label>
                        <input asp-for="photo" class="form-control-file" type="file" />
                    </div>
                    <div class="form-group pt-3 pb-3">
                        <label asp-for="newPost.Ingredients">Ингридиенты</label>
                        <textarea asp-for="newPost.Ingredients" class="form-control w-100" rows="4" style="resize: vertical;"></textarea>
                    </div>
                    <div class="form-group pt-3 pb-3">
                        <label asp-for="newPost.CookingMethod">Способ приготовления</label>
                        <textarea asp-for="newPost.CookingMethod" class="form-control w-100" rows="4" style="resize: vertical;"></textarea>
                    </div>
                    <button type="submit" class="btn btn-secondary">Добавить пост</button>
                </form>
            </div>
        }
    </div>

    <div class="pt-4">
        <div class="row gap-4 d-flex justify-content-center align-items-center">
            @foreach (var post in DbContext.Posts)
            {
                <div class="card col col-md-3 col-sm-12 mb-3" onclick="toggleRecipe('@post.PostId')">
                    <div class="card-body">
                        <div class="d-flex justify-content-center align-items-center flex-column">
                            <h2 class="card-title">@post.Name</h2>
                            <img src="@("/imgs/" + post.PhotoPath)" class="img-fluid mb-4" alt="@post.Name" />
                        </div>
                        <div class="d-none recipe-content" data-id="@post.PostId">
                            <h5 class="mt-2">Ингридиенты:</h5>
                            <p class="mt-1">@post.Ingredients</p>
                            <h5 class="mt-2">Способ приготовления:</h5>
                            <p class="mt-1">@post.CookingMethod</p>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>



</div>

@section Scripts {
    <script>
        function toggleSettingsVisibility() {
            var tasksContainer = document.getElementById('Addpost');
            var button = document.querySelector('.btn.btn-outline-secondary');

            if (tasksContainer.style.display === 'none') {
                tasksContainer.style.display = 'block';
                button.textContent = "Скрыть";
            } else {
                tasksContainer.style.display = 'none';
                button.textContent = "Добавить новый рецепт";
            }
        }


        let openRecipes = new Set();

        function toggleRecipe(PostId) {
            var recipes = document.querySelectorAll('.recipe-content');
            recipes.forEach(function (recipe) {
                if (recipe.getAttribute('data-id') === PostId) {
                    if (!openRecipes.has(recipe)) {
                        openRecipes.add(recipe); 
                        recipe.classList.remove('d-none');
                    } else {
                        openRecipes.delete(recipe); 
                        recipe.classList.add('d-none');
                    }
                } else {
                    if (openRecipes.has(recipe)) {
                        openRecipes.delete(recipe); 
                        recipe.classList.add('d-none');
                    }
                }
            });
        }
    </script>
}